export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILES = "GET_PROFILES";

//ADVERTS
export const FETCH_ADVERTS = "FETCH_ADVERTS";
export const FETCH_ADVERTS_LOADING = "FETCH_ADVERTS_LOADING";
export const ADD_ADVERT_LOADING = "ADD_ADVERT_LOADING";
export const ADD_ADVERT = "ADD_ADVERT";
export const DELETE_ADVERT = "DELETE_ADVERT";
export const EDIT_ADVERT = "EDIT_ADVERT";

//NEWS
export const FETCH_NEWS = "FETCH_NEWS";
export const FETCH_NEWS_LOADING = "FETCH_NEWS_LOADING";
export const ADD_NEWS_LOADING = "ADD_NEWS_LOADING";
export const ADD_NEWS = "ADD_NEWS";
export const DELETE_NEWS = "DELETE_NEWS";
export const EDIT_NEWS = "EDIT_NEWS";

//DOCUMENTS
export const FETCH_DOCUMENTS = "FETCH_DOCUMENTS";
export const FETCH_DOCUMENTS_LOADING = "FETCH_DOCUMENTS_LOADING";
export const ADD_DOCUMENT_LOADING = "ADD_DOCUMENT_LOADING";
export const ADD_DOCUMENT = "ADD_DOCUMENT";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";

//ALERTS
export const HIDE_ALERT = "HIDE_ALERT";
export const SHOW_ALERT = "SHOW_ALERT";
