export const ADS_SUCCESS = "ADS_SUCCESS";
export const NEWS_SUCCESS = "NEWS_SUCCESS";
export const DOCS_SUCCESS = "DOCS_SUCCESS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE";
