export const SET_CURRENT_USER = "SET_CURRENT_USER";

//PROFILES
export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS";
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const EDIT_ACCOUNT = "EDIT_ACCOUNT";
export const ACCOUNTS_LOADING = "ACCOUNTS_LOADING";

//ADVERTS
export const FETCH_ADVERTS = "FETCH_ADVERTS";
export const ADD_ADVERT = "ADD_ADVERT";
export const DELETE_ADVERT = "DELETE_ADVERT";
export const EDIT_ADVERT = "EDIT_ADVERT";
export const ADVERTS_LOADING = "ADVERTS_LOADING";

//NEWS
export const FETCH_NEWS = "FETCH_NEWS";
export const ADD_NEWS = "ADD_NEWS";
export const DELETE_NEWS = "DELETE_NEWS";
export const EDIT_NEWS = "EDIT_NEWS";
export const NEWS_LOADING = "NEWS_LOADING";

//DOCUMENTS
export const FETCH_DOCUMENTS = "FETCH_DOCUMENTS";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";
export const DOWNLOAD_DOCUMENT = "DOWNLOAD_DOCUMENT";
export const DOCUMENTS_LOADING = "DOCUMENTS_LOADING";

//ALERTS
export const HIDE_ALERT = "HIDE_ALERT";
export const SHOW_ALERT = "SHOW_ALERT";
