version: "3.8"

volumes:
  dachasql:

services:
  db:
    build: ./db/.
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YwolAaP6dBLM"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - dachasql:/var/opt/mssql
    restart: always
  api:
    build: .
    depends_on:
      - db
    ports:
      - "5000:80"
    restart: always
  client:
    build: ./Frontend/.
    depends_on:
      - api
    ports:
      - "1337:80"
    restart: always