version: "3.8"

volumes:
  dachasql:

services:
  db:
    build: ./db/.
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YwolAaP6dBLM"
      MSSQL_PID: Express
    volumes:
      - dachasql:/var/opt/mssql
    restart: always
  api:
    build: .
    depends_on:
      - db
    ports:
      - "5000:80"  
    restart: always
  client:
    build: ./Frontend/.
    environment:
      API_ADDR: api
    depends_on:
      - api
    ports:
      - "80:80"
    restart: always