version: "3.8"

volumes:
  dachasql:

services:
  db:
    build: ./Database/.
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YwolAaP6dBLM"
      MSSQL_PID: Express
    volumes:
      - dachasql:/var/opt/mssql
    restart: always
  api:
    build: ./Backend/.
    depends_on:
      - db
    restart: always
  client:
    build: ./Frontend/.
    depends_on:
      - api
    restart: always
  nginx:
    build: ./Nginx/.
    ports:
      - 80:80
      - 5000:5000
    restart: always