ALTER LOGIN sa ENABLE;
ALTER LOGIN sa WITH PASSWORD=N'aSQ3jAa5SGt1';
GO
CREATE DATABASE DachaDb;
GO
USE DachaDb;
GO
CREATE LOGIN Dacha WITH PASSWORD='aSQ3jAa5SGt5';
GO
CREATE USER DachaUser FOR LOGIN Dacha;
GO
ALTER ROLE db_owner ADD MEMBER DachaUser;
GO